# Generated by Django 5.1.4 on 2024-12-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceGenerale',
            fields=[
                ('NCG', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('DEVISE', models.CharField(max_length=50)),
                ('CPTNB', models.CharField(max_length=255)),
                ('CPTNBDB', models.CharField(max_length=255)),
                ('CPTNBCR', models.CharField(max_length=255)),
                ('SLDDEVDB', models.DecimalField(decimal_places=2, max_digits=15)),
                ('SLDDEVCR', models.DecimalField(decimal_places=2, max_digits=15)),
                ('CPTMDEVDB', models.DecimalField(decimal_places=2, max_digits=15)),
                ('CPTMDEVCR', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'db_table': 'etatbcm_balancegenerale',
            },
        ),
        migrations.CreateModel(
            name='EtatBcmBalanceDetaillee',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('BENEFICIAIRE', models.CharField(max_length=255)),
                ('DATE_TRANSACTION', models.DateField()),
                ('DEVISE', models.CharField(max_length=50)),
                ('MODE_REGLEMENT', models.CharField(max_length=50)),
                ('MONTANT_TRANSACTION', models.DecimalField(decimal_places=2, max_digits=15)),
                ('NIF_NNI', models.CharField(max_length=255)),
                ('NOM_DONNEUR_ORDRE', models.CharField(max_length=255)),
                ('PAYS', models.CharField(blank=True, max_length=100, null=True)),
                ('PRODUIT', models.CharField(blank=True, max_length=100, null=True)),
                ('REFERENCE_TRANSACTION', models.CharField(blank=True, max_length=100, null=True)),
                ('SOURCE_DEVISE', models.CharField(blank=True, max_length=100, null=True)),
                ('TAUX_CHANGE', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('TYPE_SWIFT', models.CharField(blank=True, max_length=100, null=True)),
                ('BANQUE', models.CharField(blank=True, max_length=100, null=True)),
                ('NATUREECONOMIQUE', models.CharField(blank=True, max_length=100, null=True)),
                ('NATURE_ECONOMIQUE', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'etatbcm_balancedetaillee',
            },
        ),
        migrations.CreateModel(
            name='EtatBcmFluxEntrants',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('BANQUE', models.CharField(max_length=50)),
                ('REFERENCETRANSACTION', models.CharField(max_length=100)),
                ('DATETRANSACTION', models.DateField()),
                ('TYPESWFIT', models.CharField(max_length=50)),
                ('MODEREGLEMENT', models.CharField(max_length=50)),
                ('DEVISE', models.CharField(max_length=50)),
                ('MONTANTTRANSACTION', models.DecimalField(decimal_places=2, max_digits=15)),
                ('TAUXDECHANGE', models.DecimalField(decimal_places=2, max_digits=10)),
                ('NOMDONNEURORDRE', models.CharField(max_length=100)),
                ('NIF_NNI', models.CharField(max_length=100)),
                ('BENEFICIAIRE', models.CharField(max_length=100)),
                ('PRODUIT', models.CharField(max_length=100)),
                ('NATUREECONOMIQUE', models.CharField(blank=True, max_length=100, null=True)),
                ('PAYS', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'etatbcm_flux_entrants',
            },
        ),
        migrations.CreateModel(
            name='EtatBcmFluxSortant',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('BENEFICIAIRE', models.CharField(max_length=255)),
                ('DATE_TRANSACTION', models.DateField()),
                ('DEVISE', models.CharField(max_length=50)),
                ('MODE_REGLEMENT', models.CharField(max_length=50)),
                ('MONTANT_TRANSACTION', models.DecimalField(decimal_places=2, max_digits=15)),
                ('NIF_NNI', models.CharField(max_length=255)),
                ('NOM_DONNEUR_ORDRE', models.CharField(blank=True, max_length=255, null=True)),
                ('PAYS', models.CharField(blank=True, max_length=255, null=True)),
                ('PRODUIT', models.CharField(max_length=255)),
                ('REFERENCE_TRANSACTION', models.CharField(max_length=255)),
                ('SOURCE_DEVISE', models.CharField(max_length=255)),
                ('TAUX_CHANGE', models.DecimalField(decimal_places=2, max_digits=15)),
                ('TYPE_SWIFT', models.CharField(max_length=50)),
                ('BANQUE', models.CharField(max_length=255)),
                ('NATUREECONOMIQUE', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'etatbcm_flux_sortants',
            },
        ),
    ]
