# Generated by Django 5.1.4 on 2024-12-12 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_balancegenerale_etatbcmbalancedetaillee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraub',
            name='phone',
            field=models.CharField(max_length=16),
        ),
    ]
